
  | Name       | Type       | Params
------------------------------------------
0 | activation | LeakyReLU  | 0     
1 | layer1     | Sequential | 640   
2 | layer2     | Sequential | 73.9 K
3 | layer3     | Sequential | 295 K 
4 | layer4     | Sequential | 1.2 M 
5 | fc1        | Linear     | 262 K 
6 | fc2        | Linear     | 5.1 K 
------------------------------------------
1.8 M     Trainable params
0         Non-trainable params
1.8 M     Total params
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional_tensor.py:876: UserWarning: Argument fill/fillcolor is not supported for Tensor input. Fill value is zero
  warnings.warn("Argument fill/fillcolor is not supported for Tensor input. Fill value is zero")
Epoch 0, global step 549: val_loss reached -0.28439 (best -0.28439), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v2.ckpt" as top 1
Epoch 1, global step 1099: val_loss reached -0.34990 (best -0.34990), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v2.ckpt" as top 1
Epoch 2, step 1649: val_loss was not in top 1
Epoch 3, step 2199: val_loss was not in top 1
Epoch 4, step 2749: val_loss was not in top 1
Epoch 5, step 3299: val_loss was not in top 1
Epoch 6, global step 3849: val_loss reached -0.37061 (best -0.37061), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v2.ckpt" as top 1
Epoch 7, global step 4399: val_loss reached -0.37901 (best -0.37901), saving model to "/content/gdrive/My Drive/PUSHMI/saved_models/distance_100_5e-05_0.0/model-v2.ckpt" as top 1
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)
Epoch 8, step 4484: val_loss was not in top 1

